[build]
  publish = "."

[[redirects]]
  from = "/experiment/:slug"
  to = "/experiment.html"
  status = 200

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
